In [6]:
import tensorflow as tf
import numpy as np

In [3]:
tf.executing_eagerly()

True

In [4]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
tf.constant(np.array([1.0,2.0]),dtype=tf.float32)

<tf.Tensor: id=2, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [13]:
a=tf.constant(np.array([1.0,2.0]))

In [14]:
tf.cast(a,dtype=tf.float32)

<tf.Tensor: id=5, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
tf.random.uniform((4,3), 3, 4)

<tf.Tensor: id=12, shape=(4, 3), dtype=float32, numpy=
array([[3.0119047, 3.099726 , 3.4865108],
       [3.442592 , 3.3096833, 3.716135 ],
       [3.0919645, 3.653715 , 3.17693  ],
       [3.5271654, 3.7190971, 3.1982307]], dtype=float32)>