In [43]:
import tensorflow as tf

In [2]:
a = tf.constant([[1, 2], [3, 4]])

In [3]:
tf.reshape(a, (1, 4))

<tf.Tensor: id=2, shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]])>

In [4]:
a = tf.range(24)
tf.reshape(a, (4, -1))

<tf.Tensor: id=8, shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [5]:
t = tf.constant([1, 2])
print(t.shape)
t1 = tf.expand_dims(t, -1)
print(t1.shape)

(2,)
(2, 1)


In [6]:
t1

<tf.Tensor: id=11, shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.transpose(x, perm=[1, 0])

<tf.Tensor: id=14, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [8]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])
tf.concat([t1, t2], 0)

<tf.Tensor: id=18, shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [9]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([7, 8, 9])
tf.stack([t1, t2], 1)

<tf.Tensor: id=21, shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [2, 8],
       [3, 9]])>

In [10]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])

In [11]:
tf.unstack(c, axis=0)

[<tf.Tensor: id=23, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: id=24, shape=(3,), dtype=int32, numpy=array([4, 5, 6])>]

In [12]:
tf.unstack(c, axis=1)

[<tf.Tensor: id=25, shape=(2,), dtype=int32, numpy=array([1, 4])>,
 <tf.Tensor: id=26, shape=(2,), dtype=int32, numpy=array([2, 5])>,
 <tf.Tensor: id=27, shape=(2,), dtype=int32, numpy=array([3, 6])>]

In [23]:
a = tf.constant(np.arange(10).reshape(2, 5))
tf.gather(a, axis=1, indices=[0, 2, 4])

<tf.Tensor: id=62, shape=(2, 3), dtype=int32, numpy=
array([[0, 2, 4],
       [5, 7, 9]])>

In [25]:
a = tf.constant(np.arange(10).reshape(2, 5))
tf.gather_nd(a, [[0, 0], [1, 2], [1, 4]])

<tf.Tensor: id=68, shape=(3,), dtype=int32, numpy=array([0, 7, 9])>

In [30]:
x = tf.constant([0, 1, 2])
y = tf.constant([3, 4, 5])
print(tf.add(x, y))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.divide(x, y))

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 0  4 10], shape=(3,), dtype=int32)
tf.Tensor([0.   0.25 0.4 ], shape=(3,), dtype=float64)


In [31]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 0  4 10], shape=(3,), dtype=int32)
tf.Tensor([0.   0.25 0.4 ], shape=(3,), dtype=float64)


In [36]:
x = tf.exp(3.)
tf.math.log(x)

<tf.Tensor: id=104, shape=(), dtype=float32, numpy=3.0>

In [42]:
tf.pow([1, 2, 3], [2, 3, 4])

<tf.Tensor: id=107, shape=(3,), dtype=int32, numpy=array([ 1,  8, 81])>

In [45]:
x = tf.constant(np.arange(6), shape=(2, 3))
y = tf.constant(np.arange(6), shape=(3, 2))
print(tf.matmul(x, y))
print(x@y)

tf.Tensor(
[[10 13]
 [28 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 13]
 [28 40]], shape=(2, 2), dtype=int32)


In [46]:
x = tf.random.normal([2, 3, 5])
y = tf.random.normal([5, 4])
tf.matmul(x, y)

<tf.Tensor: id=135, shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.9099537 ,  1.5138268 ,  2.4626086 , -2.7485611 ],
        [ 0.08097583, -1.4548931 ,  1.058758  ,  0.25905305],
        [ 0.7709071 ,  5.1034627 ,  4.5814896 , -3.3481464 ]],

       [[-1.004265  , -4.4032216 , -4.6109076 ,  3.2601328 ],
        [ 1.1670254 ,  1.9335797 ,  3.2185097 , -3.3024669 ],
        [-0.14443156, -3.3159518 , -2.431756  ,  1.2192018 ]]],
      dtype=float32)>

In [48]:
x = tf.constant(np.arange(12), shape=(2, 2, 3))
y = tf.constant(np.arange(12), shape=(2, 3, 2))
tf.matmul(x, y)

<tf.Tensor: id=148, shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 10,  13],
        [ 28,  40]],

       [[172, 193],
        [244, 274]]])>

In [51]:
x = tf.range(10)
print(tf.reduce_sum(x, axis=0))  # 求和
print(tf.reduce_mean(tf.cast(x, tf.float32), axis=0))  # 求平均值
print(tf.reduce_max(x, axis=0))  # 求最大值
print(tf.reduce_min(x, axis=0))  # 求最小值

tf.Tensor(45, shape=(), dtype=int32)
tf.Tensor(4.5, shape=(), dtype=float32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [55]:
print(tf.argmax(x))   #求最大值的索引
print(tf.argmin(x))   #求最大值的索引
print(tf.argsort(x,direction='DESCENDING'))  #张量排序，返回排序后的索引

tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [56]:
tf.test.is_gpu_available()

False

In [58]:
tf.config.experimental.list_physical_devices(device_type='CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]